name: token_store
version: 3.4.1
description: api for the dart pub token store.
repository: https://github.com/onepub-dev/token_store
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  cli_util: ^0.4.0
  dcli: ^8.2.0
  path: ^1.8.1
  stack_trace: ^1.10.0
dev_dependencies:
  lint_hard: ^6.2.1
  test: ^1.16.0
